schema=1
format="bitmap-glyphs"
name="Editable Spanish accents"
atlas_width=128
atlas_height=32
init_baseline=-1.0
[glyphs]
"á" = [0, 0, 5, 14, 6, 0]
"é" = [16, 0, 5, 14, 6, 0]
"í" = [32, 0, 3, 14, 6, 1]
"ó" = [48, 0, 5, 14, 6, 0]
"ú" = [64, 0, 5, 14, 6, 0]
"Á" = [80, 0, 5, 14, 6, 0]
"É" = [96, 0, 5, 14, 6, 0]
"Í" = [112, 0, 3, 14, 6, 1]
"Ó" = [0, 16, 5, 14, 6, 0]
"Ú" = [16, 16, 5, 14, 6, 0]
"ñ" = [32, 16, 5, 14, 6, 0]
"Ñ" = [48, 16, 5, 14, 6, 0]
